version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd app/
          echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
          docker build -t arthurjguerra18/continuous-delivery-eks-realworld:$TAG .
          docker push arthurjguerra18/continuous-delivery-eks-realworld:$TAG
  deploy-infra:
    docker:
        - image: hashicorp/terraform:1.2.7
    steps:
        - checkout # checkout the code
        - run: scripts/deploy-infra
  infracost:
    docker:
      - image: infracost/infracost:ci-0.10
    environment:
      TF_ROOT: infra
      BASE_BRANCH: main
      INFRACOST_ENABLE_CLOUD: "true"
    steps:
      - run:
          name: Skip if not pull request
          command: |
            if [ "$CIRCLE_PULL_REQUEST" == "" ]; then
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - checkout
      # Clone the base branch of the pull request (e.g. main/master) into a temp directory.
      - run:
          name: Checkout base branch
          command: git clone $CIRCLE_REPOSITORY_URL --branch=$BASE_BRANCH --single-branch /tmp/base
      # Generate Infracost JSON file as the baseline.
      - run:
          name: Generate Infracost cost estimate baseline
          command: |
              infracost breakdown --path=${TF_ROOT} \
                                  --format=json \
                                  --out-file=/tmp/infracost-base.json
      # Generate an Infracost diff and save it to a JSON file.
      - run:
          name: Generate Infracost cost diff estimate baseline
          command: |
              infracost diff --path=${TF_ROOT} \
                            --format=json \
                            --compare-to=/tmp/infracost-base.json \
                            --out-file=/tmp/infracost.json
      # Posts a comment to the PR using the 'update' behavior.
      - run:
          name: Post Infracost comment
          command: |
              # Extract the PR number from the PR URL
              PULL_REQUEST_NUMBER=${CIRCLE_PULL_REQUEST##*/}
              infracost comment github --path=/tmp/infracost.json \
                                       --repo=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
                                       --pull-request=$PULL_REQUEST_NUMBER \
                                       --github-token=$GITHUB_TOKEN \
                                       --behavior=update
    
workflows:
  build_and_test:
    jobs:
      - build
      - infracost
      #- deploy-infra
