version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd app/
          echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
          docker build -t arthurjguerra18/continuous-delivery-eks-realworld:$TAG .
          docker push arthurjguerra18/continuous-delivery-eks-realworld:$TAG
  create-deployment:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          AWS Region
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/continuous-delivery-eks-deployment
    
workflows:
  build:
    jobs:
      - build
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: continuous-delivery-eks
          aws-region: eu-west-1
      - create-deployment:
          cluster-name: continuous-delivery-eks
          aws-region: eu-west-1
          requires:
            - aws-eks/create-cluster
      - aws-eks/update-container-image:
          cluster-name: continuous-delivery-eks
          aws-region: eu-west-1
          container-image-updates: 'continuous-delivery-eks=continuous-delivery-eks:0.1.$CIRCLE_BUILD_NUM'
          resource-name: deployment/continuous-delivery-eks-deployment
          post-steps:
            - kubernetes/delete-resource:
                resource-names: continuous-delivery-eks-deployment
                resource-types: deployment
                wait: true
          requires:
            - create-deployment
      - aws-eks/delete-cluster:
          cluster-name: continuous-delivery-eks
          aws-region: eu-west-1
          requires:
            - aws-eks/update-container-image
