version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.2.7
    steps:
      - run: echo "hello world"
  validate-terraform:
    docker:
        - image: hashicorp/terraform:1.2.7
    steps:
        - checkout # checkout the code
        - run: ls -la && echo "hello world"
    
workflows:
  build_and_test:
    jobs:
      - build
      - validate-terraform
