version: 2.1
jobs:
  build:
    docker:
        - image: hashicorp/terraform:1.2.7
    steps:
        - checkout # checkout the code
        - run: scripts/deploy-infra
    
workflows:
  build_and_test:
    jobs:
      - build
