apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloapp
spec:
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  template:
    metadata:
      labels:
        app: realworld
        env: dev
    spec:
      containers:
      - name: realworld
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /hello
            port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1