#!/bin/sh

function validate_terraform() {
    echo "Validating Terraform code"
    cd infra
    terraform init
    terraform validate -no-color
}

function main() {
    echo "Continous Delivery EKS CI Tests"
    validate_terraform
}

main "$@"